### PR TITLE
Don't crash if burstValues() has only one argument

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]
Should this emit a warning? Because the parameter is useless in this case, no?

**Comment by swankjesse** [comment]
It’s totally unnecessary but I don’t think it’s worth a warning. Like an enum with only one constant?

**Comment by JakeWharton** [comment]
I think I would warn for that, too. Although it's less likely because the overhead of declaring an enum is higher.

**Comment by swankjesse** [comment]
Yeah good call. Added a tracking issue!

**Pull request merged**
